# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.http.response import HttpResponse
from django.conf.urls.static import static


urlpatterns = [
    # Enables DRF's API auth. Does not use JWTs:
    # url(r'^api-auth/', include('rest_framework.urls',
    #                            namespace='rest_framework')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^campaigns/list/$', 'client.views.campaignsList'),
    url(r'^clients/list/$', 'client.views.clientsList'),
    url(r'^engagements/list/$', 'client.views.engagementsList'),
    url(r'^oauth-engagements/list/$', 'client.views.engagementsList'),
    url(r'^email-servers/list/$', 'client.views.emailServersList'),
    url(r'^email-templates/list/$', 'client.views.emailTemplatesList'),
    url(r'^landing-pages/list/$', 'client.views.landingPagesList'),
    url(r'^redirect-pages/list/$', 'client.views.redirectPagesList'),
    url(r'^schedules/list/$', 'client.views.schedulesList'),
    url(r'^targets-list/list/$', 'client.views.targetsListList'),
    url(r'^users/list/$', 'client.views.usersList'),
    url(r'^vector-emails/list/$', 'client.views.vectorEmailList'),
    url(r'^slack-hooks/list/$', 'client.views.slackHooksList'),
    url(r'^scraper-user-agents/list/$', 'client.views.scraperUserAgentsList'),
    url(r'^open-redirects/list/$', 'client.views.openRedirectsList'),
    url(r'^phishing-domains/list/$', 'client.views.phishingDomainsList'),
    url(r'^oauth-consumers/list/$', 'client.views.oAuthConsumersList'),
    url(r'^oauth-results/list/$', 'client.views.oAuthResultsList'),
    url(r'^plunder/list/$', 'client.views.plunderList'),
    url(r'^shoalscrape-tasks/list/$', 'client.views.shoalScrapeTasksList'),
    url(r'^shoalscrape-creds/list/$', 'client.views.shoalScrapeCredsList'),

    url(r'^clients/edit/(?P<id>\d+)/$', 'client.views.clientEdit'),
    url(r'^users/edit/(?P<id>\d+)/$', 'client.views.userEdit'),
    url(r'^campaigns/edit/(?P<id>\d+)/$', 'client.views.campaignEdit'),
    url(r'^engagements/edit/(?P<id>\d+)/$', 'client.views.engagementEdit',
        {'is_oauth': False}),
    url(r'^oauth-engagements/edit/(?P<id>\d+)/$',
        'client.views.engagementEdit', {'is_oauth': True}),
    url(r'^email-servers/edit/(?P<id>\d+)/$', 'client.views.emailServerEdit'),
    url(r'^email-templates/edit/(?P<id>\d+)/$',
        'client.views.emailTemplateEdit'),
    url(r'^landing-pages/edit/(?P<id>\d+)/$', 'client.views.landingPageEdit'),
    url(r'^redirect-pages/edit/(?P<id>\d+)/$',
        'client.views.landingPageEdit', {'is_redirect_page': True}),
    url(r'^schedules/edit/(?P<id>\d+)/$', 'client.views.scheduleEdit'),
    url(r'^targets-list/edit/(?P<id>\d+)/$', 'client.views.targetListEdit'),
    url(r'^targets-list/edit/(?P<extend>\w+)/(?P<id>\d+)/$',
        'client.views.targetListEdit'),
    url(r'^site-settings/edit/$',
        'client.views.siteSettingsEdit'),
    url(r'^slack-hooks/edit/(?P<id>\d+)/$',
        'client.views.slackHookEdit'),
    url(r'^scraper-user-agents/edit/(?P<id>\d+)/$',
        'client.views.scraperUserAgentEdit'),
    url(r'^open-redirects/edit/(?P<id>\d+)/$',
        'client.views.openRedirectEdit'),
    url(r'^phishing-domains/edit/(?P<id>\d+)/$',
        'client.views.phishingDomainEdit'),
    url(r'^oauth-consumers/edit/(?P<id>\d+)/$',
        'client.views.oAuthConsumerEdit'),
    url(r'^oauth-results/edit/(?P<id>\d+)/$',
        'client.views.oAuthResultEdit'),
    url(r'^plunder/edit/(?P<id>\d+)/$',
        'client.views.plunderEdit'),
    url(r'^shoalscrape-tasks/edit/(?P<id>\d+)/$',
        'client.views.shoalScrapeTaskEdit'),
    url(r'^shoalscrape-creds/edit/(?P<id>\d+)/$',
        'client.views.shoalScrapeCredsEdit'),

    url(r'^clients/delete/(?P<id>\d+)/$', 'client.views.clientDelete'),
    url(r'^campaigns/delete/(?P<id>\d+)/$', 'client.views.campaignDelete'),
    url(r'^engagements/delete/(?P<id>\d+)/$', 'client.views.engagementDelete'),
    url(r'^oauth-engagements/delete/(?P<id>\d+)/$',
        'client.views.engagementDelete'),
    url(r'^email-servers/delete/(?P<id>\d+)/$',
        'client.views.emailServerDelete'),
    url(r'^email-templates/delete/(?P<id>\d+)/$',
        'client.views.emailTemplateDelete'),
    url(r'^landing-pages/delete/(?P<id>\d+)/$',
        'client.views.landingPageDelete'),
    url(r'^redirect-pages/delete/(?P<id>\d+)/$',
        'client.views.redirectPageDelete'),
    url(r'^schedules/delete/(?P<id>\d+)/$', 'client.views.scheduleDelete'),
    url(r'^users/delete/(?P<id>\d+)/$', 'client.views.userDelete'),
    url(r'^targets-list/delete/(?P<id>\d+)/$',
        'client.views.targetListDelete'),
    url(r'^vector-emails/delete/(?P<id>\d+)/$',
        'client.views.vectorEmailDelete'),
    url(r'^slack-hooks/delete/(?P<id>\d+)/$',
        'client.views.slackHookDelete'),
    url(r'^scraper-user-agents/delete/(?P<id>\d+)/$',
        'client.views.scraperUserAgentDelete'),
    url(r'^open-redirects/delete/(?P<id>\d+)/$',
        'client.views.openRedirectDelete'),
    url(r'^phishing-domains/delete/(?P<id>\d+)/$',
        'client.views.phishingDomainDelete'),
    url(r'^oauth-consumers/delete/(?P<id>\d+)/$',
        'client.views.oAuthConsumerDelete'),
    url(r'^oauth-results/delete/(?P<id>\d+)/$',
        'client.views.oAuthResultDelete'),
    url(r'^plunder/delete/(?P<id>\d+)/$',
        'client.views.plunderDelete'),
    url(r'^shoalscrape-tasks/delete/(?P<id>\d+)/$',
        'client.views.shoalScrapeTaskDelete'),
    url(r'^shoalscrape-creds/delete/(?P<id>\d+)/$',
        'client.views.shoalScrapeCredsDelete'),

    url(r'^clients/add/$', 'client.views.clientEdit'),
    url(r'^users/add/$', 'client.views.userEdit'),
    url(r'^campaigns/add/$', 'client.views.campaignEdit'),
    url(r'^engagements/add/$', 'client.views.engagementEdit'),
    url(r'^oauth-engagements/add/$', 'client.views.engagementEdit',
        {'is_oauth': True}),
    url(r'^email-servers/add/$', 'client.views.emailServerEdit'),
    url(r'^email-templates/add/$', 'client.views.emailTemplateEdit'),
    url(r'^landing-pages/add/$', 'client.views.landingPageEdit'),
    url(r'^redirect-pages/add/$', 'client.views.landingPageEdit',
        {'is_redirect_page': True}),
    url(r'^schedules/add/$', 'client.views.scheduleEdit'),
    url(r'^targets-list/add/$', 'client.views.targetListEdit'),
    url(r'^slack-hooks/add/$', 'client.views.slackHookEdit'),
    url(r'^scraper-user-agents/add/$', 'client.views.scraperUserAgentEdit'),
    url(r'^open-redirects/add/$', 'client.views.openRedirectEdit'),
    url(r'^phishing-domains/add/$', 'client.views.phishingDomainEdit'),
    url(r'^oauth-consumers/add/$', 'client.views.oAuthConsumerEdit'),
    url(r'^oauth-results/add/$', 'client.views.oAuthResultEdit'),
    url(r'^plunder/add/$', 'client.views.plunderEdit'),
    url(r'^shoalscrape-tasks/add/$', 'client.views.shoalScrapeTaskEdit'),
    url(r'^shoalscrape-creds/add/$', 'client.views.shoalScrapeCredsEdit'),

    url(r'^landing-pages/check-state/$',
        'client.views.check_landing_page_state'),
    url(r'^engagements/check-status/$',
        'client.views.check_engagement_status'),
    url(r'^engagements/check-status-campaign/$',
        'client.views.check_engagement_status_campaign'),
    url(r'^shoalscrape-tasks/check-status/$',
        'client.views.check_shoalscrape_task_status'),
    url(r'^shoalscrape-tasks/get-log/(?P<shoalscrape_task_id>\d+)/$',
        'client.views.get_shoalscrape_task_log'),
    url(r'^engagements/get-target-list/(?P<campaign_id>\d+)/$',
        'client.views.targetListByCampaign'),

    url(r'^shoalscrape-tasks/start-stop-shoalscrape-task/$',
        'client.views.start_stop_shoalscrape_task'),
    url(r'^data-management/$', 'client.views.data_management_interface'),
    url(r'^export-data/$', 'client.views.export_data'),
    url(r'^import-data/$', 'client.views.import_data'),
    url(r'^accounts/login/', 'client.views.user_login'),
    url(r'^accounts/logout/', 'client.views.user_logout'),
    url(r'^TP2pz89HC88JLog5vjmJ76CUSleovXizwHr8iIcRsEa9dm6YcIEtTyjeVU8AiYnq/',
        'client.views.user_login'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /",
                                                content_type="text/plain")),

    url(r'^clients/xml-report/(?P<client_id>[\d\w\-\_]+)/$',
        'client.xml_report.serve_xml_report'),
    url(r'^campaigns/xml-report/(?P<campaign_id>[\d\w\-\_]+)/$',
        'client.xml_report.serve_xml_report'),
    url(r'^campaigns/csv-report/(?P<campaign_id>[\d\w\-\_]+)/$',
        'client.views.serve_campaign_csv_report'),
    url(r'^engagements/xml-report/(?P<engagement_id>[\d\w\-\_]+)/$',
        'client.xml_report.serve_xml_report'),
    url(r'^engagements/csv-report/(?P<engagement_id>[\d\w\-\_]+)/$',
        'client.views.serve_engagement_csv_report'),
    url(r'^engagements/report/(?P<engagement_id>[\d\w\-\_]+)/$',
        'client.views.report'),
    url(r'^preview-engagement-email-template/(?P<engagement_id>\d+)/(?P<target_id>\d+)/$',
        'client.views.preview_engagement_email_template'),
    url(r'^engagements/preview-data/(?P<engagement_id>[\d\w\-\_]+)/$',
        'client.views.engagement_preview_data'),
    url(r'^landing-pages/preview/(?P<landing_page_id>\d+)/(?P<engagement_id>\d+)/(?P<target_id>\d+)',
        'client.views.preview_page'),
    url(r'^landing-pages/preview/(?P<landing_page_id>\d+)',
        'client.views.preview_page'),
    url(r'^plunder/serve/(?P<plunder_id>\d+)/$', 'client.views.serve_plunder'),
    url(r'^email-servers/test/$', 'client.views.check_email'),
    url(r'^phishing-domains/test/$', 'client.views.check_domain'),
    url(r'^email-templates/preview/(?P<id>\d+)$',
        'client.views.emailTemplatePreview'),
    url(r'^email-templates/get-variables/$',
        'client.views.email_template_get_variables'),
    url(r'^email-templates/check-shortcodes/$',
        'client.views.check_email_template_shortcodes'),
    url(r'^email-templates/decode-quopri/$', 'client.views.decode_quopri'),
    url(r'^landing-pages/check-form/$',
        'client.views.check_landing_page_form'),

    # Google APIs
    url(r'^oauth-apis/google/all/api-console/(?P<oa_result_id>\d+)/$',
        'client.views.google_api_console',
        {'console_type': None}),
    url(r'^oauth-apis/google/gmail/api-console/(?P<oa_result_id>\d+)/$',
        'client.views.google_api_console',
        {'console_type': 'gmail'}),
    url(r'^oauth-apis/google/drive/api-console/(?P<oa_result_id>\d+)/$',
        'client.views.google_api_console',
        {'console_type': 'drive'}),

    url(r'^oauth-apis/google/gmail/messages/list/(?P<oa_result_id>\d+)/$',
        'client.views.gmail_messages_list'),
    url(r'^oauth-apis/google/gmail/messages/verbose-list/(?P<oa_result_id>\d+)/$',
        'client.views.gmail_messages_verbose_list'),
    url(r'^oauth-apis/google/gmail/messages/get-everything/(?P<oa_result_id>\d+)/$',
        'client.views.gmail_messages_get_everything'),
    url(r'^oauth-apis/google/gmail/messages/get/(?P<oa_result_id>\d+)/(?P<message_id>\w+)/$',
        'client.views.gmail_messages_get'),

    url(r'^oauth-apis/google/drive/files/list/(?P<oa_result_id>\d+)/$',
        'client.views.drive_files_list'),
    url(r'^oauth-apis/google/drive/files/download/(?P<oa_result_id>\d+)/$',
        'client.views.drive_files_download'),

    # Sandbar APIs
    url(r'^api/(?P<version>v1|v2)/', include('api.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'client.views.external_404'
